export const sidebar: string;
export const bg_image: string;
export const user: string;
export const menu_wrapper: string;
export const menu: string;
export const link: string;
export const active: string;
export const name: string;
export const contact: string;
