export const auth_wrapper: string;
export const animation_container: string;
export const register: string;
export const auth_block: string;
export const content_block: string;
export const reg_block: string;
export const bg_image: string;
export const title: string;
export const description: string;
